locals {
  storage_account_length = length(var.sub) < 6 ? 14 : 20
  
  # Helper function to build name parts conditionally
  routing_part = var.routing_domain != "" ? "-${var.routing_domain}" : ""
  app_id_part  = var.application_id != "" ? "-${var.application_id}" : ""
}

output "standard" {
  description = "Return list of calculated standard names for deployment of Azure resources"
  value = {
    resource-group  = lower("rg-${var.location-map[var.location]}${local.app_id_part}-${var.context}-${var.environment}-${var.inc}")
    virtual-network = lower("vnet-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    subnet          = lower("snet-${var.location-map[var.location]}-${var.security_zone}-${replace(var.subnet_cidr, ".", "_")}-${split("/", var.subnet_cidr)[1]}")
    #subnet                     = lower("snet-azu${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    route-table                          = lower("rt-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.context}-${var.environment}-${var.inc}")
    application-security-group           = lower(var.application_id != "" ? "asg-${var.location-map[var.location]}-${var.application_id}-${var.environment}-${var.inc}" : "asg-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    key-vault                            = lower(var.application_id != "" ? "kv${replace(var.location-map[var.location], "azu", "")}${var.application_id}${var.environment}${var.inc}" : "kv${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}")
    network-security-group               = lower("nsg-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.security_zone}-${var.environment}-${var.inc}")
    public-ip-address                    = lower("pip-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.context}-${var.environment}-${var.inc}")
    local-network-gateway                = lower("lgw-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.context}-${var.inc}")
    vnet-gateway-connection              = lower("con-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.context}-${var.inc}")
    vnet-gateway                         = lower("vgw-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    ip-group                             = lower("ipg-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    bastion                              = lower("bas-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    firewall                             = lower("afw-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    firewall-policy                      = lower("afwp-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    nva-fgt                              = lower("nva-fgt-azu${var.location-map[var.location]}-${var.application_id}-${var.context}-${var.environment}-${var.inc}")
    nva-fgt-nic                          = lower("nva-fgt-nic-${var.location-map[var.location]}-${var.application_id}-${var.context}-${var.environment}-${var.inc}")
    private-dns-resolver                 = lower("dnspr-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    inbound-endpoints-dns                = lower("in-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    outbound-endpoints-dns               = lower("out-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    dns-forwarding-ruleset               = lower("dnsfrs-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-hub                            = lower("evh-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-hub-namespace                  = lower("evhns-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    eventhub-ns-authorization-rule       = lower("evhnsar-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    eventhub-authorization-rule          = lower("evhar-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-grid-system-topic              = lower("egst-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    event-grid-system-topic-subscription = lower("evsts-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    logic-app                            = lower("logic-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    storage-account                      = lower("st${replace(var.location-map[var.location], "azu", "")}${var.local_market_shortcut}${var.context}${var.environment}${var.inc}")
    log-analytics-workspace              = lower("log-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    application-insights                 = lower("appi-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    api-connection                       = lower("api-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    virtual-machine                      = lower(var.local_market != "" ? "vm${replace(var.location-map[var.location], "azu", "")}${var.local_market}${var.context}${var.inc}" : "vm${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}")
    ddos-protection-plan                 = lower("ddos-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    load-balancer                        = lower(var.routing_domain != "" ? "lbi-${var.location-map[var.location]}-${var.routing_domain}-${var.context}-${var.environment}-${var.inc}" : "ilb-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    shared-image-gallery                 = lower("sig${var.environment}${replace(var.location-map[var.location], "azu", "")}${var.context}")
    keyvault-key                         = lower("kvk-${var.location-map[var.location]}-cmk${var.key_func}-${var.environment}-${var.inc}")
    express-route-circuit                = lower("erc-${var.location-map[var.location]}${local.routing_part}${local.app_id_part}-${var.environment}-${var.inc}")
    data-disk                            = lower(var.local_market != "" ? "vm${replace(var.location-map[var.location], "azu", "")}${var.local_market}${var.context}${var.inc}-datadisk-${var.data_disk_inc}" : "vm${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}-datadisk-${var.data_disk_inc}")
    os-disk                              = lower("vm-${replace(var.location-map[var.location], "azu", "")}-${var.context}${can(regex("vg", var.context)) ? "" : var.environment}${var.inc}-osdisk")
    private-endpoint                     = lower("pep-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    managed_devops_pool                  = lower("mdp-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    automation_account                   = lower("aa-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    dev_center                           = lower("dc-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}") #name cannot exceed 26 characters
    virtual-machine-scale-set            = lower("vmss${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}")
    auto-scaling                         = lower("scaling${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}")
    nat_gateway                          = lower("ng-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    disk-encryption-set                  = lower(var.application_id != "" ? "des-${var.location-map[var.location]}-${var.application_id}-${var.environment}-${var.inc}" : "des-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    app-service-plan                     = lower("asp-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    web-app                              = lower("app-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    function-app                         = lower("func-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    dashboard                            = lower("dash-${var.location-map[var.location]}-mon-${var.environment}-${var.inc}")
    mysql-db-server                      = lower("mysql-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    sql-managed-instance                 = lower("sqlmi-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    sql-database                         = lower("sqldb-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    sql-server                           = lower("sql-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    app-gateway                          = lower("agw${replace(var.location-map[var.location], "azu", "")}${var.local_market_shortcut}${var.context}${var.environment}${var.inc}")
    agw-front-end-pvt                    = lower("agfe-pvt-${var.context}-ipv4-${var.inc}")
    agw-front-end-pub                    = lower("agfe-pub-${var.context}-ipv4-${var.inc}")
    agw-backend-pool                     = lower("agbp-${var.context}-${var.agwbe_port}-${var.inc}")
    agw-health-probe                     = lower("aghp-${var.context}-${var.agwhp_type}-${var.inc}")
    agw-routing-rule                     = lower("agr-${var.context}-${var.agwrrl_type}-${var.inc}")
    agw-backend-settings                 = lower("agbs-${var.context}-${var.agwbs_type}-${var.inc}")
    agw-listener                         = lower("ls-agw-${var.context}-${var.agwls_port}-${var.inc}")
    agw-rewrite-set                      = lower("rws-${var.context}-${var.inc}")
    api-management                       = lower("apim-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    container-app                        = lower("ca-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    aks                                  = lower("aks${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}")
    ml-workspace                         = lower("mlw-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    user-assigned-identity               = lower("id-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    container-registry                   = lower("cr${replace(var.location-map[var.location], "azu", "")}${var.context}${var.environment}${var.inc}")
    cognitive-services                   = lower("cog-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    search                               = lower("srch-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    cosmosdb                             = lower("cosmos-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
    container-app-environment            = lower("cae-${var.location-map[var.location]}-${var.context}-${var.environment}-${var.inc}")
  }
}
